version: '3'
services:
  #mysql用コンテナ
  mysql:
    container_name: mysql
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: yurikaN4IBI

  #phpMyAdmin用コンテナ
  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - 8888:80

  #php用コンテナ
  php:
    container_name: php-apache
    build: ./php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    ports:
      - 8080:80
    